# Generated by Django 3.2.13 on 2023-10-11 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_alter_chatbotuser_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='messages',
        ),
        migrations.AddField(
            model_name='message',
            name='message_user',
            field=models.CharField(choices=[('BOT', 'BOT'), ('AGENT', 'AGENT'), ('CUSTOMER', 'CUSTOMER')], default='CUSTOMER', max_length=100),
        ),
    ]
